package mchorse.bbs_mod.graphics.window;

import org.lwjgl.input.Keyboard;
import java.util.HashMap;
import java.util.Map;

/** Stable BBS shortcut IDs (the saved 1.20.4 values), translated only at the native input boundary. */
public final class InputCodes
{
    public static final int RELEASE=0, PRESS=1, REPEAT=2;
    public static final int MOUSE_BUTTON_LEFT=0, MOUSE_BUTTON_RIGHT=1, MOUSE_BUTTON_MIDDLE=2;
    public static final int ARROW_CURSOR=0x36001, IBEAM_CURSOR=0x36002, CROSSHAIR_CURSOR=0x36003,
        HAND_CURSOR=0x36004, HRESIZE_CURSOR=0x36005, VRESIZE_CURSOR=0x36006;
    public static final int KEY_UNKNOWN = -1;
    public static final int KEY_SPACE = 32;
    public static final int KEY_APOSTROPHE = 39;
    public static final int KEY_COMMA = 44;
    public static final int KEY_MINUS = 45;
    public static final int KEY_PERIOD = 46;
    public static final int KEY_SLASH = 47;
    public static final int KEY_0 = 48;
    public static final int KEY_1 = 49;
    public static final int KEY_2 = 50;
    public static final int KEY_3 = 51;
    public static final int KEY_4 = 52;
    public static final int KEY_5 = 53;
    public static final int KEY_6 = 54;
    public static final int KEY_7 = 55;
    public static final int KEY_8 = 56;
    public static final int KEY_9 = 57;
    public static final int KEY_SEMICOLON = 59;
    public static final int KEY_EQUAL = 61;
    public static final int KEY_A = 65;
    public static final int KEY_B = 66;
    public static final int KEY_C = 67;
    public static final int KEY_D = 68;
    public static final int KEY_E = 69;
    public static final int KEY_F = 70;
    public static final int KEY_G = 71;
    public static final int KEY_H = 72;
    public static final int KEY_I = 73;
    public static final int KEY_J = 74;
    public static final int KEY_K = 75;
    public static final int KEY_L = 76;
    public static final int KEY_M = 77;
    public static final int KEY_N = 78;
    public static final int KEY_O = 79;
    public static final int KEY_P = 80;
    public static final int KEY_Q = 81;
    public static final int KEY_R = 82;
    public static final int KEY_S = 83;
    public static final int KEY_T = 84;
    public static final int KEY_U = 85;
    public static final int KEY_V = 86;
    public static final int KEY_W = 87;
    public static final int KEY_X = 88;
    public static final int KEY_Y = 89;
    public static final int KEY_Z = 90;
    public static final int KEY_LEFT_BRACKET = 91;
    public static final int KEY_BACKSLASH = 92;
    public static final int KEY_RIGHT_BRACKET = 93;
    public static final int KEY_GRAVE_ACCENT = 96;
    public static final int KEY_ESCAPE = 256;
    public static final int KEY_ENTER = 257;
    public static final int KEY_TAB = 258;
    public static final int KEY_BACKSPACE = 259;
    public static final int KEY_INSERT = 260;
    public static final int KEY_DELETE = 261;
    public static final int KEY_RIGHT = 262;
    public static final int KEY_LEFT = 263;
    public static final int KEY_DOWN = 264;
    public static final int KEY_UP = 265;
    public static final int KEY_PAGE_UP = 266;
    public static final int KEY_PAGE_DOWN = 267;
    public static final int KEY_HOME = 268;
    public static final int KEY_END = 269;
    public static final int KEY_CAPS_LOCK = 280;
    public static final int KEY_SCROLL_LOCK = 281;
    public static final int KEY_NUM_LOCK = 282;
    public static final int KEY_PRINT_SCREEN = 283;
    public static final int KEY_PAUSE = 284;
    public static final int KEY_F1 = 290;
    public static final int KEY_F2 = 291;
    public static final int KEY_F3 = 292;
    public static final int KEY_F4 = 293;
    public static final int KEY_F5 = 294;
    public static final int KEY_F6 = 295;
    public static final int KEY_F7 = 296;
    public static final int KEY_F8 = 297;
    public static final int KEY_F9 = 298;
    public static final int KEY_F10 = 299;
    public static final int KEY_F11 = 300;
    public static final int KEY_F12 = 301;
    public static final int KEY_F13 = 302;
    public static final int KEY_F14 = 303;
    public static final int KEY_F15 = 304;
    public static final int KEY_F16 = 305;
    public static final int KEY_F17 = 306;
    public static final int KEY_F18 = 307;
    public static final int KEY_F19 = 308;
    public static final int KEY_F20 = 309;
    public static final int KEY_F21 = 310;
    public static final int KEY_F22 = 311;
    public static final int KEY_F23 = 312;
    public static final int KEY_F24 = 313;
    public static final int KEY_F25 = 314;
    public static final int KEY_KP_0 = 320;
    public static final int KEY_KP_1 = 321;
    public static final int KEY_KP_2 = 322;
    public static final int KEY_KP_3 = 323;
    public static final int KEY_KP_4 = 324;
    public static final int KEY_KP_5 = 325;
    public static final int KEY_KP_6 = 326;
    public static final int KEY_KP_7 = 327;
    public static final int KEY_KP_8 = 328;
    public static final int KEY_KP_9 = 329;
    public static final int KEY_KP_DECIMAL = 330;
    public static final int KEY_KP_DIVIDE = 331;
    public static final int KEY_KP_MULTIPLY = 332;
    public static final int KEY_KP_SUBTRACT = 333;
    public static final int KEY_KP_ADD = 334;
    public static final int KEY_KP_ENTER = 335;
    public static final int KEY_KP_EQUAL = 336;
    public static final int KEY_LEFT_SHIFT = 340;
    public static final int KEY_LEFT_CONTROL = 341;
    public static final int KEY_LEFT_ALT = 342;
    public static final int KEY_LEFT_SUPER = 343;
    public static final int KEY_RIGHT_SHIFT = 344;
    public static final int KEY_RIGHT_CONTROL = 345;
    public static final int KEY_RIGHT_ALT = 346;
    public static final int KEY_RIGHT_SUPER = 347;
    public static final int KEY_MENU = 348;
    private static final Map<Integer,Integer> TO_NATIVE=new HashMap<>(), FROM_NATIVE=new HashMap<>();
    static {
        bind(KEY_0, "0");
        bind(KEY_1, "1");
        bind(KEY_2, "2");
        bind(KEY_3, "3");
        bind(KEY_4, "4");
        bind(KEY_5, "5");
        bind(KEY_6, "6");
        bind(KEY_7, "7");
        bind(KEY_8, "8");
        bind(KEY_9, "9");
        bind(KEY_A, "A");
        bind(KEY_B, "B");
        bind(KEY_C, "C");
        bind(KEY_D, "D");
        bind(KEY_E, "E");
        bind(KEY_F, "F");
        bind(KEY_G, "G");
        bind(KEY_H, "H");
        bind(KEY_I, "I");
        bind(KEY_J, "J");
        bind(KEY_K, "K");
        bind(KEY_L, "L");
        bind(KEY_M, "M");
        bind(KEY_N, "N");
        bind(KEY_O, "O");
        bind(KEY_P, "P");
        bind(KEY_Q, "Q");
        bind(KEY_R, "R");
        bind(KEY_S, "S");
        bind(KEY_T, "T");
        bind(KEY_U, "U");
        bind(KEY_V, "V");
        bind(KEY_W, "W");
        bind(KEY_X, "X");
        bind(KEY_Y, "Y");
        bind(KEY_Z, "Z");
        bind(KEY_F1, "F1");
        bind(KEY_F2, "F2");
        bind(KEY_F3, "F3");
        bind(KEY_F4, "F4");
        bind(KEY_F5, "F5");
        bind(KEY_F6, "F6");
        bind(KEY_F7, "F7");
        bind(KEY_F8, "F8");
        bind(KEY_F9, "F9");
        bind(KEY_F10, "F10");
        bind(KEY_F11, "F11");
        bind(KEY_F12, "F12");
        bind(KEY_F13, "F13");
        bind(KEY_F14, "F14");
        bind(KEY_F15, "F15");
        bind(KEY_F16, "F16");
        bind(KEY_F17, "F17");
        bind(KEY_F18, "F18");
        bind(KEY_F19, "F19");
        bind(KEY_F20, "F20");
        bind(KEY_F21, "F21");
        bind(KEY_F22, "F22");
        bind(KEY_F23, "F23");
        bind(KEY_F24, "F24");
        bind(KEY_F25, "F25");
        bind(KEY_KP_0, "NUMPAD0");
        bind(KEY_KP_1, "NUMPAD1");
        bind(KEY_KP_2, "NUMPAD2");
        bind(KEY_KP_3, "NUMPAD3");
        bind(KEY_KP_4, "NUMPAD4");
        bind(KEY_KP_5, "NUMPAD5");
        bind(KEY_KP_6, "NUMPAD6");
        bind(KEY_KP_7, "NUMPAD7");
        bind(KEY_KP_8, "NUMPAD8");
        bind(KEY_KP_9, "NUMPAD9");
        bind(KEY_SPACE, "SPACE");
        bind(KEY_APOSTROPHE, "APOSTROPHE");
        bind(KEY_COMMA, "COMMA");
        bind(KEY_MINUS, "MINUS");
        bind(KEY_PERIOD, "PERIOD");
        bind(KEY_SLASH, "SLASH");
        bind(KEY_SEMICOLON, "SEMICOLON");
        bind(KEY_EQUAL, "EQUALS");
        bind(KEY_LEFT_BRACKET, "LBRACKET");
        bind(KEY_BACKSLASH, "BACKSLASH");
        bind(KEY_RIGHT_BRACKET, "RBRACKET");
        bind(KEY_GRAVE_ACCENT, "GRAVE");
        bind(KEY_ESCAPE, "ESCAPE");
        bind(KEY_ENTER, "RETURN");
        bind(KEY_TAB, "TAB");
        bind(KEY_BACKSPACE, "BACK");
        bind(KEY_INSERT, "INSERT");
        bind(KEY_DELETE, "DELETE");
        bind(KEY_RIGHT, "RIGHT");
        bind(KEY_LEFT, "LEFT");
        bind(KEY_DOWN, "DOWN");
        bind(KEY_UP, "UP");
        bind(KEY_PAGE_UP, "PRIOR");
        bind(KEY_PAGE_DOWN, "NEXT");
        bind(KEY_HOME, "HOME");
        bind(KEY_END, "END");
        bind(KEY_CAPS_LOCK, "CAPITAL");
        bind(KEY_SCROLL_LOCK, "SCROLL");
        bind(KEY_NUM_LOCK, "NUMLOCK");
        bind(KEY_PRINT_SCREEN, "SYSRQ");
        bind(KEY_PAUSE, "PAUSE");
        bind(KEY_KP_DECIMAL, "DECIMAL");
        bind(KEY_KP_DIVIDE, "DIVIDE");
        bind(KEY_KP_MULTIPLY, "MULTIPLY");
        bind(KEY_KP_SUBTRACT, "SUBTRACT");
        bind(KEY_KP_ADD, "ADD");
        bind(KEY_KP_ENTER, "NUMPADENTER");
        bind(KEY_KP_EQUAL, "NUMPADEQUALS");
        bind(KEY_LEFT_SHIFT, "LSHIFT");
        bind(KEY_LEFT_CONTROL, "LCONTROL");
        bind(KEY_LEFT_ALT, "LMENU");
        bind(KEY_LEFT_SUPER, "LMETA");
        bind(KEY_RIGHT_SHIFT, "RSHIFT");
        bind(KEY_RIGHT_CONTROL, "RCONTROL");
        bind(KEY_RIGHT_ALT, "RMENU");
        bind(KEY_RIGHT_SUPER, "RMETA");
        bind(KEY_MENU, "APPS");
    }
    private static void bind(int code,String name) {
        int nativeCode=Keyboard.getKeyIndex(name);
        if(nativeCode!=Keyboard.KEY_NONE) { TO_NATIVE.put(code,nativeCode); FROM_NATIVE.put(nativeCode,code); }
    }
    public static int toNative(int code) { return TO_NATIVE.getOrDefault(code,-1); }
    public static int fromNative(int code) { return FROM_NATIVE.getOrDefault(code,KEY_UNKNOWN); }
    public static String keyName(int code) { int key=toNative(code); return key<0?null:Keyboard.getKeyName(key); }
    public static final int RESIZE_NWSE_CURSOR = 0x36007;
    public static final int RESIZE_NESW_CURSOR = 0x36008;
    private InputCodes() {}
}
